### PR TITLE
Update some indicators for TWW

### PR DESCRIPTION
**Pull request by atti92**

### CODE REVIEW

**Comment by trenchtoaster** [comment]
Okay, looks like Eternal Flame HoT is within this pull request.

**Comment by atti92** [comment]
@enderneko Prepatch is out, safe to merge now?

**Comment by enderneko** [comment]
> @enderneko Prepatch is out, safe to merge now?

yeah, later today, just got to the office.
awesome work! 👍

**Comment by enderneko** [comment]
Thanks for your contribution!

**Pull request merged**
