### PR TITLE
Snippet for enabled click cast on non-cell frames

### PR DESCRIPTION
**Pull request by atti92**
I heard the feedback that this is a very much needed feature, so I tried to create a small snippet instead of trying to force the feature into the core.

I needed to export a new function for Updating click castings to make this proper and not a hack, otherwise the whole snippet is a copy paste of the ClickCastings.lua

Changes:
- F:UpdateClickCastOnFrame: This new function is what is called on all frames for updating click casts. (needed for the snippet)

### CODE REVIEW

**Comment by enderneko** [comment]
cool!

**Comment by atti92** [comment]
Have to fix the snippet to

```
local F = Cell.funcs

local blizzardFrames = {
    "PlayerFrame",
    "TargetFrame",
    "PetFrame",
    "PartyMemberFrame1",
    "PartyMemberFrame2",
    "PartyMemberFrame3",
    "PartyMemberFrame4",
    "PartyMemberFrame1PetFrame",
    "PartyMemberFrame2PetFrame",
    "PartyMemberFrame3PetFrame",
    "PartyMemberFrame4PetFrame",
}

local function IterateOnExternalFrames(func)
    local ClickCastFrames = _G.ClickCastFrames or {}
    for frame, _ in pairs(ClickCastFrames) do
        func(frame)
    end
    for _, name in pairs(blizzardFrames) do
        local frame = _G[name]
        if frame then
            func(frame)
        end
    end
end



IterateOnExternalFrames(function(frame)
        frame:RegisterForClicks("AnyDown")
        frame:EnableMouse(true)
        frame:EnableKeyboard(true)
        frame:EnableMouseWheel(true)
    end
)


local function UpdateClickCastings(noReload, onlyqueued)
    F:UpdateClickCastings(noReload, onlyqueued)
    
    local snippet = F:GetBindingSnippet()
    IterateOnExternalFrames(function (frame)
            F:UpdateClickCastOnFrame(frame, snippet)
            frame:SetAttribute("OnEnter", frame:GetAttribute("_onenter"))
            frame:SetAttribute("OnLeave", frame:GetAttribute("_onleave"))
            frame:SetAttribute("OnHide", frame:GetAttribute("_onhide"))
            
            CellWrapFrame:UnwrapScript(frame, "OnEnter")
            CellWrapFrame:WrapScript(frame, "OnEnter", [[
                if mouseoverbutton then mouseoverbutton:ClearBindings() end
                mouseoverbutton = self
                self:Run(self:GetAttribute("snippet"))
            ]])
            
        end
    )
end


local function UpdateQueuedClickCastings()
    UpdateClickCastings(true, true)
end

Cell:UnregisterCallback("UpdateClickCastings",  "UpdateClickCastings")
Cell:UnregisterCallback("UpdateQueuedClickCastings",  "UpdateQueuedClickCastings")

Cell:RegisterCallback("UpdateQueuedClickCastings", "UpdateQueuedClickCastings", UpdateQueuedClickCastings)
Cell:RegisterCallback("UpdateClickCastings",  "UpdateClickCastings", UpdateClickCastings)
```

**Comment by Biomedic32** [comment]
If we wanted to add more frames (this doesnt include boss frames from the looks of it, which some raid fights have you heal friendly units which show as bosses) I'm assuming we would just add the frames to the blizzardFrames block? Is that just BossFrame1 etc?

**Comment by atti92** [comment]
> If we wanted to add more frames (this doesnt include boss frames from the looks of it, which some raid fights have you heal friendly units which show as bosses) I'm assuming we would just add the frames to the blizzardFrames block? Is that just BossFrame1 etc?

yes

**Comment by lv100mewtwo** [comment]
any way to add shadowed unit frames easily?

**Comment by JysCl** [comment]
Would love for it to be able to work for mouseover casts also. Currently, I can only use click casts.

**Pull request merged**
